# Generated by Django 5.0 on 2024-02-01 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userProfile', '0003_customuser_is_merchant_alter_customuser_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='zipcode',
            field=models.CharField(blank=True, help_text='Enter your Zip Code or Postal Address', max_length=6, null=True, verbose_name='Zip Code/ Postal Address'),
        ),
    ]
